config/routes.rb
Rails.application.routes.draw do

  # one page route
  root "main#home"

  # user authentication routes
  get "sign_up", to: "users#sign_up_view"
  get "sign_in", to: "users#sign_in_view"
  delete "sign_out", to: "users#delete_session"

  resources :users, only: [] do
    post "create_session", on: :collection
    post "create_new", on: :collection
  end

  devise_for :users

  # routes of saved events
  resources :bookmarks, only: [:index, :create, :destroy] do
    post "check", on: :collection # check if events are already bookmarked
  end

  # routes for API
  # there are two sets of routes. The first uses remote database and the second
  # use local database. (by default the local database is used)
  resources :events, only: [:create, :index]
  resources :local_events, only: [:create, :index]

  resources :usages, only: [:index] # only show usage info


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :rememberable,
         #:recoverable, # remove unwanted features
         #:validatable,
         :registerable
  has_many :bookmarks, dependent: :destroy
  has_many :usages, dependent: :destroy

  validates :email, uniqueness: true

  def add_search_usage_record(ip, status)
    self.usages.create request_type: Usage::SEARCH_REQUEST, ip: ip, status: status
  end

  def add_create_usage_record(ip, status)
    self.usages.create request_type: Usage::CREATE_REQUEST, ip: ip, status: status
  end
end

app/controllers/users_controller.rb
class UsersController < ActionController::Base
  layout "application"

  def sign_in_view
    @user = User.new
  end

  def sign_up_view
    @user = User.new
  end

  def delete_session
    sign_out current_user
    redirect_to root_path
  end

  def create_session
    email = params[:user][:email]
    @user = User.find_by email: email
    if email.blank?
      @error = "Please enter an email"
    elsif @user.nil?
      @error = "This email is not registered"
    elsif !@user.valid_password?(params[:user][:password])
      @error = "Password is incorrect"
    else
      sign_in @user
    end
  end

  def create_new
    email = params[:user][:email]
    if email.blank?
      @error = "Please enter an email"
    elsif User.where(email: email).exists?
      @error = "This email already exists"
    else
      @user = User.new email: email, password: params[:user][:password], password_confirmation: params[:user][:password_confirmation]
      logger.info ">>>>>>> 1"
      if @user.save
        logger.info ">>>>>>> 2"
        sign_in @user
      else
        logger.info ">>>>>>> 3"
        @error = @user.errors.full_messages.join(", ")
        @error = "Email already exists" if @error.blank?
      end
    end
  end



end

app/views/users/create.js.erb
<% if @error.blank? %>
$(".error-message").text("");
window.location.href="/";
<% else %>
$(".error-message").text(`<%= @error %>`);
<% end %>

app/views/users/create_new.js.erb
<% if @error.blank? %>
$(".error-message").text("");
window.location.href="/";
<% else %>
$(".error-message").text(`<%= @error %>`);
<% end %>

app/views/users/create_session.js.erb
<% if @error.blank? %>
$(".error-message").text("");
window.location.href="/";
<% else %>
$(".error-message").text(`<%= @error %>`);
<% end %>

app/views/users/sign_in_view.html.erb
<div class="container d-flex justify-content-center">
  <div class="auth card shadow-sm p-5">
    <h4>Sign In</h4>
    <p>Please sign in to test saving events.</p>

    <p class="text-danger error-message"></p>

    <%= form_for(User.new, url: create_session_users_path, remote: true, html: { data: { turbo: false} }) do |f| %>
      <div class="mb-3">
        <%= f.label :email, class: "form-label" %>
        <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= f.label :password, class: "form-label" %>
        <%= f.password_field :password, autocomplete: "current-password", class: "form-control" %>
      </div>

      <div class="mb-4">
        <div class="form-check">
          <%= f.check_box :remember_me, class: "form-check-input" %>
          <%= f.label :remember_me, class: "form-check-label" do %>
            Remember me
          <% end %>
        </div>
      </div>

      <div class="actions d-flex justify-content-center mb-3">
        <%= f.submit "Sign in", class: "btn btn-primary" %>
      </div>
      <p class="text-center m-0">
        <%= link_to "I don't have an account", sign_up_path %><br />
        <%= link_to "Back to home", root_path %>
      </p>

    <% end %>
  </div>
</div>

app/views/users/sign_up_view.html.erb
<div class="container d-flex justify-content-center">
  <div class="auth card shadow-sm p-5">
    <h4>Sign Up</h4>
    <p>Register an new account to test saving events. You can use any email it will not be verified.</p>

    <p class="text-danger error-message"></p>

    <%= form_for(@user, url: create_new_users_path, remote: true, html: { data: { turbo: false} }) do |f| %>
      <div class="mb-3">
        <%= f.label :email, class: "form-label" %>
        <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= f.label :password, class: "form-label" %>
        <%= f.password_field :password, autocomplete: "new-password", class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= f.label :password_confirmation, class: "form-label" %>
        <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control" %>
      </div>


      <div class="actions d-flex justify-content-center mb-3">
        <%= f.submit "Register", class: "btn btn-primary" %>
      </div>
      <p class="text-center m-0">
        <%= link_to "I already have an account", sign_in_path %><br/>
        <%= link_to "Back to home", root_path %>
      </p>

    <% end %>
  </div>
</div>