config/routes.rb
Rails.application.routes.draw do

  # one page route
  root "main#home"

  # user authentication routes
  get "sign_up", to: "users#sign_up_view"
  get "sign_in", to: "users#sign_in_view"
  delete "sign_out", to: "users#delete_session"

  resources :users, only: [] do
    post "create_session", on: :collection
    post "create_new", on: :collection
  end

  devise_for :users

  # routes of saved events
  resources :bookmarks, only: [:index, :create, :destroy] do
    post "check", on: :collection # check if events are already bookmarked
  end

  # routes for API
  # there are two sets of routes. The first uses remote database and the second
  # use local database. (by default the local database is used)
  resources :events, only: [:create, :index]
  resources :local_events, only: [:create, :index]

  resources :usages, only: [:index] # only show usage info


end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg fixed-top navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "REQ92534 Assessment Question 1", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;"></ul>

      <div class="d-flex">
        <% if !user_signed_in? %>
          <%= link_to "Sign In", sign_in_path, class: "btn btn-secondary btn-sm ms-2 me-1" %>
          <%= link_to "Sign Up", sign_up_path, class: "btn btn-success btn-sm ms-2 me-1" %>
        <% else %>
          <button class="btn btn-sm btn-link" disabled><%= current_user.email %></button>
          <%= link_to "Sign Out", sign_out_path, method: :delete, class: "btn btn-danger btn-sm ms-2 me-1" %>
        <% end %>
      </div>
    </div>
  </div>
</nav>